name: Create release file

on:
  workflow_dispatch:
  

jobs:

  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        
    - run: echo "version=$(grep "version" build.gradle.kts | tail -n 1 | cut -d "=" -f2  )" >> $GITHUB_OUTPUT
      id: value
      shell: bash
    - run: echo "${{steps.value.outputs.version}}" 
    
    - name: Setup and execute Gradle 'build' task
      uses: gradle/gradle-build-action@v2
      id: build
      with:
        arguments: build
    - run: echo "${{steps.build.outputs}}"
