name: Create release file

on:
  workflow_dispatch:
  

jobs:

  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    
    - name: Setup and execute Gradle 'properties' task
      uses: gradle/gradle-build-action@v2
      id: properties
      with:
        arguments: version
    - name: Getting version from Build.Gradle.kts
    - run:   echo ::set-env name=version::$(grep "version" build.gradle.kts)
      shell: bash
      
    - name: Check if I can still use the outputs from the Grep Build.gradle.kts file
    - run: echo steps.env.outputs.version
