name: Create release file

on:
  workflow_dispatch:
  

jobs:

  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    
    - name: Setup and execute Gradle 'properties' task
      uses: gradle/gradle-build-action@v2
      id: properties
      with:
        arguments: properties
    - run: echo "SELECTED_COLOR= $(grep "version" build.gradle.kts | tail -n 1)" >> $GITHUB_OUTPUT
      shell: bash
    - run: echo "${{steps.properties.outputs.version}}" 
    - run: echo ::get-output name=version::$
